### ISSUE TITLE
Actually run it on buttwoo

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2#10]
related https://github.com/ssbc/ssb-tribes2/issues/9

right now i'm adapting this pr https://github.com/ssbc/ssb-tribes2/pull/8 to assume we're publishing on buttwoo instead of classic (like old tribes1). i've swapped json.stringify for bipf size checking but the size is still limited to 8k. buttwoo supposedly has a limit of 16k which changes things.

**Comment by Powersource** [comment]
sidequest https://github.com/ssbc/ssb-keys/pull/101

**Comment by staltz** [comment]
We decided to postpone using buttwoo until we can properly address (perhaps in a dedicated grant project) how to support per-message deletion in buttwoo, and we need resources to harden (fix bugs, polish, test and analyse) buttwoo for use in production.
