### ISSUE TITLE
Require tangles.group.previous to be at least size 1

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2#11]
In the current tanglePrune code from tribes1 it is able to prune until the `previous` array is empty. Is that a good idea or likely to break tangle logic?

https://github.com/ssbc/ssb-tribes2/blob/ff6905b7638220073f8c292cee648d8e99cc8a49/lib/tangle-prune.js#L23-L28

**Comment by mixmix** [comment]
Nice catch. I think it should prune down to one at lowest

**Comment by Powersource** [comment]
The new logic has fixed this

https://github.com/ssbc/ssb-tribes2/blob/206138ecabb88f0f807e4d3e2218808d53db79ab/lib/prune-publish.js#L5-L22
