### ISSUE TITLE
lib/epochs (getPreferredEpoch - 4.7. disjoint membership)

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2#115]
https://github.com/ssbc/ssb-tribes2/blob/e3591f6620a3e8ecd50e693579d604d4aa65c147/test/lib/epochs.test.js#L335C12-L339

**Comment by mixmix** [comment]
Resolved: https://github.com/ssbc/ssb-tribes2/blob/master/test/lib/epochs.test.js#L527
