### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2#15]

**Comment by Powersource** [comment]
@arj03 you requested this. Do you have a gold standard recommended way of doing this?

**Comment by arj03** [comment]
A good place to start would be here I think: https://github.com/ssbc/ssb-db2/commit/ab0d3cec1f89cb8df8481421749c1a60db6316c1

**Comment by arj03** [comment]
But there should also be something in this module that does some of the same things, with adding 1000 messages.

**Comment by arj03** [comment]
Now adding it maybe not the best test because it's not realistic that someone creates a lot of messages, but I want to be sure that the tangle stuff scales well when you have a lot of messages in a group.

**Comment by arj03** [comment]
Yeah. Thanks :)
