### ISSUE TITLE
Update tangle libraries to LGPL-3.0

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-tribes2#32]
* [x] @tangle/graph https://gitlab.com/tangle-js/tangle-graph/-/merge_requests/10
* [x] @tangle/reduce https://gitlab.com/tangle-js/tangle-reduce/-/merge_requests/7
* [x] @tangle/strategy https://gitlab.com/tangle-js/strategies/strategy/-/merge_requests/5
* [x] envelope-spec needs new release
* [x] is-my-ssb-valid https://github.com/ssbc/is-my-ssb-valid/pull/7

**Comment by Powersource** [comment]
https://gitlab.com/tangle-js/tangle-reduce/-/merge_requests/7

**Comment by Powersource** [comment]
Useful command

```
pnpm licenses list|rg -w 'AGPL|GPL'
```

**Comment by Powersource** [comment]
```
│ @tangle/graph                              │ AGPL-3.0               │
│ @tangle/reduce                             │ AGPL-3.0               │
│ @tangle/strategy                           │ AGPL-3.0               │
│ envelope-spec                              │ AGPL-3.0               │
│ is-my-ssb-valid                            │ AGPL-3.0               │
```

**Comment by Powersource** [comment]
@mixmix see above for PRs and stuff :)

**Comment by mixmix** [comment]
@Powersource done
