### ISSUE TITLE
Size limit to groups?

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2#38]
Some fb groups have millions of members. I don't think we'd support that very well, especially when we get member removal.

**Comment by Powersource** [comment]
We'll at least need to decide if we want to do this before we put it in prod

**Comment by staltz** [comment]
While SSB (in total) itself still has less than 100k users, I don't think we should be worrying about limits at the point we are right now.

**Comment by Powersource** [comment]
I don't see the harm in limiting it, but either way I guess users will notice things will get laggy/buggy if they get to too big sizes, so I guess we can drop this for now.
