### ISSUE TITLE
Re-add checking of add-member spec

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2#43]
It's disabled for some reason

https://github.com/ssbc/ssb-tribes2/blob/206138ecabb88f0f807e4d3e2218808d53db79ab/index.js#L21

https://github.com/ssbc/ssb-tribes2/blob/206138ecabb88f0f807e4d3e2218808d53db79ab/index.js#L196-L198

**Comment by staltz** [comment]
It's disabled because the spec checks were failing due to outdated specs.

**Comment by Powersource** [comment]
waiting on https://github.com/ssbc/private-group-spec/pull/23
