### ISSUE TITLE
Unpin meta-feeds version

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2#48]
context https://github.com/ssbc/ssb-tribes2/pull/46

**Comment by Powersource** [comment]
@arj03 do you have a hunch if this might be a bug in meta-feeds or if i'm holding it wrong?

**Comment by arj03** [comment]
strange. I can reproduce this locally, so could have a look @Powersource

**Comment by arj03** [comment]
Wooooooooooooooooooo, I think I found it

**Comment by arj03** [comment]
Lol, we are now in the mode where this fail because `authorIsBendyButtV1` is not working :smiling_imp:
