### ISSUE TITLE
Make stuff work on feed encodings other than buttwoo

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-tribes2#9]
Working on https://github.com/ssbc/ssb-tribes2/pull/8 there's code in `tanglePrune` that assumed how the content of a msg is stringified. In tribes1 it assumed classic with json.stringify, now I'm thinking of assuming buttwoo with bipf. But it should probably be generalized or at least documented that it (or at least that feature) only supports 1 format.

**Comment by staltz** [comment]
Shouldn't be an issue any more.
